In [4]:
import numpy as np
import numpy.linalg as linalg

## Vector operations

In the previous workshop, we saw how to use the NumPy library to create and perform mathematical operations on numerical arrays (including vectors, which are considered to be 1D NumPy arrays).  Below is a brief example of vector addition:

In [2]:
x = np.array([2, 1, -3])
y = np.array([-3, 0, -1])
print('x + y = \n', x + y)

x + y = 
 [-1  1 -4]


**Your turn:** Search the NumPy linear algebra documentation https://docs.scipy.org/doc/numpy-1.15.1/reference/routines.linalg.html to find the appropriate functions for computing norms and dot products of vectors. Then:

1. Compute the norm of the vector $\vec{x}$ = [1,2,3,4,5,6,7,8,9,10].
2. Compute the dot product $\vec{x} \cdot \vec{y}$ for the vector $\vec{x}$ above and $\vec{y}$ = [-1,3,5,12,15,0,4,0.5,-2.5,3]. 

In [19]:
x = [1,2,3,4,5,6,7,8,9,10]
y = [-1,3,5,12,15,0,4,0.5,-2.5,3]
np.dot(x,y)

# or
x2 = np.array([1,2,3,4,5,6,7,8,9,10])
y2 = np.array([-1,3,5,12,15,0,4,0.5,-2.5,3])
print(linalg.multi_dot([x2,y2]))


182.5


## Basic matrix operations

In the previous workshop, we also saw how to do some basic matrix operations using NumPy. Today we'll deploy more of NumPy's matrix capabilities using its `linalg` routine.

First, let's create the matrix $C$ from Example 2.1:

In [7]:
C = np.array([[1, 3], [-2, 1]])
print(C)

[[ 1  3]
 [-2  1]]


And now let's create the 2x2 identity matrix $I_2$ using the `identity` function:

In [5]:
I2 = np.identity(2)
print(I2)

[[1. 0.]
 [0. 1.]]


Now we can do a variety of matrix options, such as addition, multiplication of matrix by scalar, or even matrix multiplication:

In [ ]:
print('C + I_2 = \n', C + I2)  # adding two matrices

In [ ]:
print('-3C = \n', -3*C)  # multiplying a matrix by a scalar

In [ ]:
print('C x I2 = \n', np.matmul(C, I2))  # multiplying two matrices

**Your turn #1:** Multiply the two matrices given in Example 3.c.2.

In [9]:
a = np.array([[1,2,-1,8,5],[-2,1,0,4,5],[3,1.5,0.5,4,5]])
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[-17,-18,-19,-20]])

print(np.matmul(a,b))

[[ 21.  26.  31.  36.]
 [-30. -32. -34. -36.]
 [-18. -14. -10.  -6.]]


**Your turn #2:** Search the NumPy `linalg` documentation to find the functions for computing the inverse and determinant of a square matrix.  Then: 

1. Compute the inverse of the matrix $C$. Compare your answer to Example 3.e.1.
2. Compute the determinant of the matrix $G$ from example 3.e.2.

In [16]:
c = np.array([[1, 3], [-2, 1]])
print(linalg.inv(c), "\n")

g = np.array([[1,3,0],[-2,2,0],[-2,1,0]])
print("det g is ", linalg.det(g))

[[ 0.14285714 -0.42857143]
 [ 0.28571429  0.14285714]] 

det g is  0.0


## Eigenvalues, eigenvectors, and matrix diagonalization

In this notebook we'll follow Example 5.1 and diagonalize the following matrix:

$$
A =
\begin{bmatrix}
1 & 4 \\
2 & 3
\end{bmatrix}
$$

In [23]:
A = np.array([[1, 4],[2, 3]])
print(A)

[[1 4]
 [2 3]]


As we saw before, we'll need the eigenvalues and eigenvectors of this matrix to find its diagonalized form, $D = P^{-1} A P$:

In [24]:
linalg.eig(A)

(array([-1.,  5.]), array([[-0.89442719, -0.70710678],
        [ 0.4472136 , -0.70710678]]))

It looks like the eigenvalues of the matrix are returned in the first array, while the *normalized* eigenvectors are returned in the second array (as a matrix!).  [What does it mean to normalize a vector? See http://mathworld.wolfram.com/NormalizedVector.html for more info.] 

Let's take the eigen*vectors* and form the matrix $P$:

In [32]:
P = linalg.eig(A)[1]
print(P)

[[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


Then to find $D$, we actually calculate $P^{-1} A P$:

In [36]:
print(np.matmul(np.matmul(linalg.inv(P), A), P))
# ^e-16 is 0"



[[-1.0000000e+00  8.8817842e-16]
 [ 0.0000000e+00  5.0000000e+00]]
e-16 is 0


Note that we have to use two successive applications of the `matmul()` function to multiply three matrices together.

You may have also noticed that $D$ is nothing more than a diagonal matrix with the eigen*values* being the diagonal entries. This suggests that we could form $D$ directly by extracting the eigenvalues of $A$ and placing them on the diagonal:

In [27]:
D = np.diag(linalg.eig(A)[0])
print(D)

[[-1.  0.]
 [ 0.  5.]]


One thing that matrix diagonalization is useful for is calculating powers of matrices. For example, suppose that you want to calculate $A^3$. (power to diagonal) This can be accomplished by calculating $P D^3 P^{-1}$ (where $D^3$ can be calculated simply by cubing each of the entries of $D$):

In [28]:
np.matmul(np.matmul(P, D**3), linalg.inv(P))  # calculate A^3 by doing P D^3 P^-1

array([[41., 84.],
       [42., 83.]])

You might suspect, however, that NumPy has a way to calculate powers of square matrices in an even more direct way.

**Your turn:** Search the NumPy `linalg` documentation to find a function that can compute powers of square matrices directly. Use it to calculate $A^3$.

In [37]:
linalg.matrix_power(A, 3)

array([[41, 84],
       [42, 83]])

In [8]:
#example 6.a.2: deduce BCS index formula
#BCS = x1(USA) + x2(Harris) + x3(computer)
#find x1, x2, x3

#[1482*x1 + 2699*x2+ 100*x3] = 0.9757
#[1481*x1+ 2776*x2+ 89*x3] = 0.9479
#[1408*x1+ 2616*x2 + 94*x3 ] = 0.9298
# m is ranking, n is BCS index
m = np.array([[1482,2699,100],[1481,2776,89],[1408,2616,94]])
n = np.array([0.9757, 0.9479, 0.9298])

formula = linalg.solve(m,n)
print(formula)

[0.0002151  0.00011949 0.00334417]


In [9]:
#prove
np.dot(m,formula)

array([0.9757, 0.9479, 0.9298])

In [10]:
# calculate BCS Index with formula
np.dot(formula, np.array([1300,2600,79]))

0.8544952575220968